### ISSUE TITLE
Import Error Roadblock

### ISSUE THREAD

**Issue by the-Joe** [chartmogul/chartmogul-python#2]
Very basic initial tests with this resulted in issues. Anyone find a resolution?

Simple ping script per documentation:
`import chartmogul

config = chartmogul.Config('TOKEN','SECRET')
chartmogul.Ping.ping(config).get()'

Result:
'Traceback (most recent call last):
  File "./ping.py", line 2, in <module>
    import chartmogul
  File "/Library/Python/2.7/site-packages/chartmogul/__init__.py", line 2, in <module>
    from .api.config import Config
ImportError: No module named api.config`

**Comment by pkopac** [comment]
Hello @the-Joe!
This is an installation issue and has been resolved in https://github.com/chartmogul/chartmogul-python/pull/1
I am sorry for the inconvenience, please upgrade to the new version [1.0.2](https://pypi.python.org/pypi?:action=display&name=chartmogul&version=1.0.2).
