### ISSUE TITLE
Invoices plan_uuid should be optional 

### ISSUE THREAD

**Issue by ruimangas** [chartmogul/chartmogul-python#25]
Due to empty plan_uuid fields, our ETL is breaking with promise not valid error ```marshmallow.exceptions.ValidationError: {118: {'line_items': {0: {'plan_uuid': ['Field may not be null.']}}}}``` not allowing us to get any invoices even though only one invoice has empty plan_uuid.

I'm wondering if plan_uuid could be considered optional (and what the overall impact would be) by changing, ```plan_uuid = fields.String(allow_none=True)``` inside ```invoices.py```

**Comment by pkopac** [comment]
Hi @ruimangas,

you are correct. I am sorry for the inconvenience that this caused.

The line is here:
https://github.com/chartmogul/chartmogul-python/blob/master/chartmogul/api/invoice.py#L15

It should be optional.
https://dev.chartmogul.com/reference#import-customers-invoices

>Optional for one_time line items.

I'll fix it right away.

**Comment by ruimangas** [comment]
Thanks on behalf the Priori Data dev team 👍

**Comment by pkopac** [comment]
@ruimangas just released as 1.2.2. If fixed, please close this ticket.
