### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'strict'

### ISSUE THREAD

**Issue by matuspavliscak** [chartmogul/chartmogul-python#28]
Hello, a few hours ago I started experiencing issues with your Python wrapper getting this error (when importing chartmogul):

```
Python transformation failed: __init__() got an unexpected keyword argument 'strict'
Traceback (most recent call last):
File "<string>", line 5, in <module>
File "/usr/local/lib/python3.7/site-packages/chartmogul/__init__.py", line 5, in <module>
from .api.activity import Activity
File "/usr/local/lib/python3.7/site-packages/chartmogul/api/activity.py", line 6, in <module>
class Activity(Resource):
File "/usr/local/lib/python3.7/site-packages/chartmogul/api/activity.py", line 29, in Activity
_schema = _Schema(strict=True)
TypeError: __init__() got an unexpected keyword argument 'strict'
Script failed.
```

I dug into your code only to find out that marshmallow has updated to 3.0.0 and this causes the issue in your code. I quickly fixed this by installing marshmallow version 2.20.1. Maybe you want to fix that as well.

**Comment by mattwensing** [comment]
Thanks @matuspavliscak - I just ran into the same thing.  Figured it was a versioning issue with marshmallow.  How did you figure out which previous version of marshmallow to use?

**Comment by matuspavliscak** [comment]
@mattwensing Importing started failing when Marshmallow 3.0.0 was introduced, so I decided to try the last version of marshmallow before that one and it worked. I also created a support ticket with Chartmogul’s support.

**Comment by pkopac** [comment]
@matuspavliscak thank you for reporting and suggesting the fix. We've released a fix update under `1.2.3`
https://github.com/chartmogul/chartmogul-python/releases/tag/v1.2.3

**Comment by MasoudRahimy** [comment]
when i got this error, usually i have to go to my class and change the attribute name to something else
watch out for keywords.

**Comment by pkopac** [comment]
Hello @MasoudRahimy , does this mean you are still experiencing the exact same issue with the library on the latest version (1.3.0)?
If so, what version of Python do you use and do you have any hints how we can replicate the issue?

Thank you

**Comment by MasoudRahimy** [comment]
@pkopac my python version is 3.7.6 using new pycharm version on mac
open keyword in class below generate the error.()if you need more of the code let me know
`class Stock:
    def __init__(self, symbol, date, open_, high, low, close, volume):
        self.symbol = symbol
        self.date = date
        self.open = open_
        self.high = high
        self.low = low
        self.close = close
        self.volume = volume`


`class StockSchema(Schema):
    symbol = fields.Str()
    date = fields.Date()
    open = fields.Decimal(as_string=True)
    high = fields.Decimal(as_string=True)
    low = fields.Decimal(as_string=True)
    close = fields.Decimal(as_string=True)
    volume = fields.Integer()
    
    @post_load()
    def make_stock(self, data):
        return Stock(**data)`

**Comment by pkopac** [comment]
@MasoudRahimy please check out the latest version 1.5.0 and verify if it solves your issue, thank you.

**Comment by Aaron-MSB** [comment]
I am experiencing thesame error and this 2022/2023. Using python3. What should I do please

**Comment by Aaron-MSB** [comment]
Traceback (most recent call last):
  File "/home/aaron/Documents/FLASK_SQLALCHEMY_REST/app.py", line 37, in <module>
    product_schema = ProductSchema(strict=True)
TypeError: Schema.__init__() got an unexpected keyword argument 'strict'

**Comment by pkopac** [comment]
Hi @Aaron-MSB, I am a bit confused by your question. The error is coming from your application (`app.py`). Looking at the changelog the library [has removed this keyword argument in 3.0.0 back in 2018](https://marshmallow.readthedocs.io/en/stable/changelog.html#b7-2018-02-03). We don't use it in our repository either. Do you actually have an issue with the ChartMogul library?
