### ISSUE TITLE
Tests in 3.5 fail due to dependencies

### ISSUE THREAD

**Issue by jdevera** [chartmogul/chartmogul-python#33]
vcrpy depends on yarl in python >= 3.5 but yarl needs Python 3.6 at least. This breaks the tests.

**Comment by jdevera** [comment]
Tracked in their repo https://github.com/kevin1024/vcrpy/issues/485

**Comment by jdevera** [comment]
#32 includes a workaround to run the tests, basically pinning, for Python 3.5 only,  an older version of yarl that supports Python 3.5

**Comment by neozenith** [comment]
Fixed in kevin1024/vcrpy#489, looking to get a release out soon. Thanks for reporting.

**Comment by neozenith** [comment]
And got the release out:
https://github.com/kevin1024/vcrpy/releases/tag/v2.1.1
