### ISSUE TITLE
making sense of chartmogul.Customer.modify

### ISSUE THREAD

**Issue by tisdall** [chartmogul/chartmogul-python#57]
I think I've managed to suss out how this works, but the documentation and code needs some updating.

The README.md has this example that seems like a bad copy-paste from `merge`:
```python
chartmogul.Customer.modify(config, uuid='cus_5915ee5a-babd-406b-b8ce-d207133fb4cb', data={
  'from': {'customer_uuid': 'cus_5915ee5a-babd-406b-b8ce-d207133fb4cb'},
  'into': {'customer_uuid': 'cus_2123290f-09c8-4628-a205-db5596bd58f7'}
})
```
Maybe should be replaced with something like (taken from [the API docs](https://dev.chartmogul.com/reference/update-a-customer)):
```python
chartmogul.Customer.modify(config, uuid='cus_5915ee5a-babd-406b-b8ce-d207133fb4cb', data={
  "city": "San Francisco",
  "country": "US",
  "state": "CA",
})
```

Also, both the [Update a Customer docs](https://dev.chartmogul.com/reference/update-a-customer) and code seem to imply you can call `modify` without any UUID.  I haven't tried it, but I suspect it doesn't work.  If it should be required, it seems like `modify` (and any of the other `patch` actions) should be added here:  https://github.com/chartmogul/chartmogul-python/blob/377fa17e26cac4ada20f013f8aec43a0d4b5bab1/chartmogul/resource.py#L150-L154  If it does work without a UUID, it'd be nice if the docs explained how it resolves which document it updates and which pieces of information in `data` are required for that to work.

Incidentally, it seems like the library allows a `chartmogul.Customer.update` call which does a PUT.  I'm not sure if this actually works, but if the API allows it then it seems like a "foot gun" where people will by trying to "Update a Customer" but actually replacing the whole document with just the parts they want to update.

**Comment by pkopac** [comment]
Hello @tisdall,

thank you for the report.

The API only allows `PATCH` for modifications of a Customer.

Please use the reference documentation [dev.chartmogul.com/reference](https://dev.chartmogul.com/reference/update-a-customer), where the examples are correct. I changed README, so it's not confusing :+1: 

>both the [Update a Customer docs](https://dev.chartmogul.com/reference/update-a-customer) and code seem to imply you can call modify without any UUID

It requires UUID. Could you please be more specific in how does it imply this? I don't see it.

**Comment by tisdall** [comment]
To clarify about updating a customer...
 - the examples in the docs show adding a UUID, but the explanation of fields below doesn't show something like this (taken from the Customer.delete): 
![image](https://user-images.githubusercontent.com/4029388/161328678-e4699d34-d751-449f-a097-85ddb1a8ce04.png)
 - I linked to the code where it validates that `kwargs` contains the needed values, but when `method` is `modify` it doesn't go into that `if` statement when `uuid` is not set.  So, it looks like it won't raise a `ArgumentMissingError` in that case.

**Comment by tisdall** [comment]
I think all the issues mentioned here have been addressed, so closing issue.
