### ISSUE TITLE
chartmogul.Subscription doesn't exist

### ISSUE THREAD

**Issue by tisdall** [chartmogul/chartmogul-python#62]
It looks like in 8cc4c6e this was renamed to `chartmogul.CustomerSubscription` but not all the documentation was updated.  Under the ["Import API" docs](https://dev.chartmogul.com/reference/list-a-customers-subscriptions) it still has the old name.  It's also not updated [in the README.md under "Subscriptions"](https://github.com/chartmogul/chartmogul-python#subscriptions).

**Comment by pkopac** [comment]
Thank you for reporting this, @tisdall, we're sorry for the inconvenience. We'll fix it ASAP.

**Comment by SrikalaB** [comment]
Fixed in v3.0.2

**Comment by tisdall** [comment]
Is this something that hasn't been pushed up yet?  I don't see any changes.

**Comment by SrikalaB** [comment]
> Is this something that hasn't been pushed up yet? I don't see any changes.

Namespace has been added back in v 3.0.2. It is available for download - https://pypi.org/project/chartmogul/

Readme has been updated with the recommended usage:
https://github.com/chartmogul/chartmogul-python#subscriptions - for modifying a subscription. Please note that this works only with custom data source.
https://github.com/chartmogul/chartmogul-python#metrics-api - for viewing metrics related to a subscription.

Changes in #64

**Comment by tisdall** [comment]
Ah.. I see now.  Thanks!

**Comment by tisdall** [comment]
Not sure if you have a separate tracker for the API docs, but it still seems to be the old name on ["List Customer's Subscriptions"](https://dev.chartmogul.com/reference/list-a-customers-subscriptions) and ["Cancel a Customer's Subscription"](https://dev.chartmogul.com/reference/cancel-a-customers-subscription)
