### ISSUE TITLE
effective_date and event_date data types in subscription_event.py

### ISSUE THREAD

**Issue by Sutton128** [chartmogul/chartmogul-python#76]
I'm trying to use the chartmogul.SubscriptionEvent.create() method using the provided code sample and keep getting the following error: `marshmallow.exceptions.ValidationError: {'effective_date': ['Not a valid date.'], 'event_date': ['Not a valid date.']}`

I've tried different date formats including using the date package to no avail.

I found that if I change the data type definitions in subscription_event.py from fields.Date() to fields.DateTime() everything works as expected. Also, I notice that almost everywhere a date is used it is a DateTime data type except for here and once instance in metrics.py.

I don't see that this has been reported by anyone else, so possibly there's some other issue. I also don't know if simply changing the data types is an appropriate action. But please let me know how to proceed.

**Comment by pkopac** [comment]
Hi @Sutton128! Thank you for reporting and sorry for the inconvenience. We're merging a fix for this bug soon #77 please wait for a patch release.

**Comment by Sutton128** [comment]
Thanks for taking a look at this. I'll keep an eye out for the release.

**Comment by kmossco** [comment]
@Sutton128 it has been a while but considering we haven't heard any further complaints about this issue since the release for #77, I'll close this one. Let us know if you bump into any other issues though!
