### ISSUE TITLE
chartmogul.Invoice.all() - failing because of has_more

### ISSUE THREAD

**Issue by benread2k** [chartmogul/chartmogul-python#80]
I'm running into the same issue as this – https://github.com/chartmogul/chartmogul-python/issues/79

```
req = chartmogul.Invoice.all(config, per_page=pp)
response = req.get()
```

The code above produces the error \<lambda\>() got an unexpected keyword argument 'has_more'

This script has been running perfectly for several months, so it seems like a recent change

**Comment by swember** [comment]
Hello @benread2k, thank you for the report. We're working on improvements on our API and this shouldn't have happened. The fix is in production now and the library works as expected.

**Comment by dalbello** [comment]
Hi @swember and @pkopac, I'm seeing this issue too. Are you sure this fix was deployed? Or maybe it bug has made its way back into production again? 
Code: 
`invoices = chartmogul.Invoice.all(config,external_id=order_id).get();
`

Error:
`TypeError: <lambda>() got an unexpected keyword argument 'has_more'`
