### ISSUE TITLE
Unexpected 'cursor' in response to chartmogul.Activity.all()

### ISSUE THREAD

**Issue by benread2k** [chartmogul/chartmogul-python#82]
I'm getting a TypeError `<lambda>() got an unexpected keyword argument 'cursor'` after several months of successfully using the same API call `req = chartmogul.Activity.all(config, start_date=from_date, per_page=pp)`

Have there been any API changes that might be causing this? Is there anything else that I might be missing?

**Comment by swember** [comment]
Hello, yes, there is an API change. We've updated it, so the issue should be gone soon.
