### ISSUE TITLE
chartmogul.Customer.all fails due to incorrect field setup in Customer model

### ISSUE THREAD

**Issue by timecamp-analityk** [chartmogul/chartmogul-python#91]
customer.py line 69 is
`website_url = fields.String()`
should be
`website_url = fields.String(allow_none=True)`

this causes request to fail request validation in example code
```
chartmogul_config = chartmogul.Config(chartmogul_API_key)
chartmogul.Customer.all(chartmogul_config, cursor=cursor).get()
```

modifying field property fixes this issue in chartmogul-4.2.0

**Comment by whobubble** [comment]
Hi, thanks for reporting this. We'll provide a new version with a fix soon.
