### ISSUE TITLE
Security Vulnerability in urllib3 Dependency

### ISSUE THREAD

**Issue by davidlacho** [chartmogul/chartmogul-python#95]
## Description
A security vulnerability has been identified in the urllib3 package used in the chartmogul-python library. The details of this vulnerability can be found [here](https://data.safetycli.com/packages/pypi/urllib3/).

## Impact:

- The vulnerability poses potential risks that could affect the security of applications using this library.
- There are dependency conflicts for users who need to use the most recent version of urllib3. These conflicts hinder the adoption of security patches and improvements provided in the latest urllib3 versions.

## Suggested Solution:

- Review the security advisory linked above.
- Update the urllib3 dependency to a secure version as recommended.
- Resolve any compatibility issues that arise from updating urllib3 to ensure smooth integration.
- Perform necessary tests to ensure compatibility and stability after the update.

**Comment by pkopac** [comment]
Thank you @davidlacho, we have released [4.3.1](https://pypi.org/project/chartmogul/4.3.1/).
