### ISSUE TITLE
Integrate External ID Lookup for Customers in SDK

### ISSUE THREAD

**Issue by davidlacho** [chartmogul/chartmogul-python#99]
**Description:**

Hello ChartMogul Team,

I am currently working with the ChartMogul API and came across a requirement that I believe would significantly enhance the Python SDK's functionality and is required for our specific use case.

### Current Situation

As it stands, the ChartMogul API allows retrieving a customer record by `external_id` using a cURL call, as shown below:

```bash
curl -X GET "https://api.chartmogul.com/v1/customers?external_id={stripe_cus_id}" \
-u YOUR_API_KEY:
```

In Python, this can be accomplished using the `requests` library:

```python
import requests
from requests.auth import HTTPBasicAuth

url = 'https://api.chartmogul.com/v1/customers'
params = {
    'external_id': 'zeta01'
}

# Make the request
response = requests.get(url, params=params, auth=HTTPBasicAuth(api_key, api_secret))
```

However, this functionality is not currently available in the Python SDK, which necessitates using a workaround using the `requests` library, instead of having a built-in method.

### Request

I would like to request the integration of the ability to retrieve customers by `external_id` directly within the ChartMogul Python SDK. This would streamline the process and improve the overall developer experience by aligning the SDK capabilities with those available through direct API calls, and would help us in our specific use-case.

### Benefits

- **Improved Efficiency:** Developers can retrieve customer data using `external_id` without writing additional code for HTTP requests.
- **Consistency:** Aligns the SDK with the available API capabilities, providing a more unified development experience.
- **Ease of Use:** Simplifies the integration process for developers, reducing the need for manual HTTP request handling.

### Conclusion

Integrating this feature into the Python SDK would be greatly appreciated and beneficial to many users who rely on the SDK for efficient API interactions. Thank you for considering this request. I look forward to your response.

Best regards,

David

**Comment by tudorpavel** [comment]
Hi David,

Thanks for the detailed ticket. I believe the API you are using to find a Customer by `external_id` is the [List Customers](https://dev.chartmogul.com/reference/list-customers) endpoint which is in fact available in the SDK under `Customer.all`.

So your example would look something like this using the SDK:
```py
import chartmogul

config = chartmogul.Config('api_key')

chartmogul.Customer.all(config, external_id='zeta01')
```

Please note that External IDs are only unique within a particular DataSource so we recommend including `data_source_uuid` in your filters whenever possible.

Hope that helps!
Tudor

**Comment by davidlacho** [comment]
> Hi David,
> 
> 
> 
> Thanks for the detailed ticket. I believe the API you are using to find a Customer by `external_id` is the [List Customers](https://dev.chartmogul.com/reference/list-customers) endpoint which is in fact available in the SDK under `Customer.all`.
> 
> 
> 
> So your example would look something like this using the SDK:
> 
> ```py
> 
> import chartmogul
> 
> 
> 
> config = chartmogul.Config('api_key')
> 
> 
> 
> chartmogul.Customer.all(config, external_id='zeta01')
> 
> ```
> 
> 
> 
> Please note that External IDs are only unique within a particular DataSource so we recommend including `data_source_uuid` in your filters whenever possible.
> 
> 
> 
> Hope that helps!
> 
> Tudor

Thanks Tudor! I'll give that a shot! The support rep didn't inform us of this and told us to use the request library, so I'll give it a go!
